# DO NOT CHANGE the "init" and "install" sections below
cache:
  - C:\RLibrary

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest https://raw.githubusercontent.com/jimhester/r-appveyor/patch-1/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh install_github hadley/dplyr

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip


environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    USE_RTOOLS: true

  matrix:
  - R_VERSION: devel
    GCC_PATH: mingw_32

  - R_VERSION: devel
    R_ARCH: x64
    GCC_PATH: mingw_64

  - R_VERSION: release
    R_ARCH: x64

  - R_VERSION: stable

  - R_VERSION: patched

  - R_VERSION: oldrel
    RTOOLS_VERSION: 33
    CRAN: http://cran.rstudio.com

  - R_VERSION: 3.1.3
    RTOOLS_VERSION: 32
    CRAN: http://cran.rstudio.com


artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
